/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/residential_building.glb --types 
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/residential_building.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        [name: string]: THREE.Mesh
    }
    materials: {
        [name: string]: THREE.Material
    }
}

export function ResidentialModel(props: React.JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/models/residential_building-compressed.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            {Object.entries(nodes).map(([name, node]) => {
                if (node.isMesh) {
                    return (
                        <mesh
                            key={name}
                            geometry={node.geometry}
                            material={node.material}
                            castShadow
                            receiveShadow
                        />
                    )
                }
                return null;
            })}
        </group>
    )
}

useGLTF.preload('/models/residential_building-compressed.glb')
